# Generated by Django 4.1.7 on 2023-03-25 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_ccl_left'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ccl_left',
            field=models.FloatField(default=0),
        ),
    ]
