# Generated by Django 4.1.7 on 2023-04-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_customuser_sid'),
    ]

    operations = [
        migrations.AddField(
            model_name='ccls',
            name='half',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cls',
            name='half',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='epl_left',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='ssl_left',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sls',
            name='half',
            field=models.BooleanField(default=False),
        ),
    ]
