# Generated by Django 4.1.7 on 2023-04-21 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_ccls_half_cls_half_profile_epl_left_profile_ssl_left_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EPLS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('half', models.BooleanField(default=False)),
                ('on_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epls', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
