# Generated by Django 4.1.7 on 2023-03-25 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_ccl_left'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='ccl_left',
            field=models.IntegerField(null=True, verbose_name='ccl_left'),
        ),
    ]
