# Generated by Django 4.1.7 on 2023-03-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_profile_ccl_left'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holidays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_date', models.DateField()),
                ('desc', models.CharField(max_length=200)),
            ],
        ),
    ]
