# Generated by Django 4.1.7 on 2023-04-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_holidays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='sid',
            field=models.CharField(max_length=10, verbose_name='sid'),
        ),
    ]
